version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: twitter_postgres
    environment:
      POSTGRES_DB: twitter_clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - twitter_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: twitter_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - twitter_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitter_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/twitter_clone
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - twitter_network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:

networks:
  twitter_network:
    driver: bridge 